language: java

jdk:
  - oraclejdk11
  - oraclejdk8

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"

env:
  global:
    - secure: JB+UfbeJUMbOTpunDxBWD6SwOjbTMg/ID8bBjUqsmTJJ6/DMF1g/EqJvvThTx8yDF2r4yOyZGwlQGyZ3NBBzgXhdDJuRlsP6/FiQzSvl3STpqiFPwh+tIG1irr6yDdOGbH0xmb+eMuSGNLu9QLkcHk9TguPboNM7FTV5z5Y7RUGCL5j10GdZ5XcYyoHurZ/WzZo6BDi7yia033rn1svcZpPD+ZLIEaxIFb66Zbtn7Y0OqYlxylS8Ro+2siCuivfghXxhQvMpUsaYXaMjGGcB1PqWnK7qHeDoDmQcj9AhdIaPXINx+XYZQFVfCV/bgdBF3mclWnlyiN/CErDPLGUvH8Zfai2EfmLKKRga8hnxK7M1mCe0KOGCCsna5v/xSaDdCV8UOgbXjWKzh0NPBDbrHkaJZAb/uIzfqq4Sanwoltfu0XB1PQeE4AehpBdIfOTJnPJ/YgtuTPWyQWP24Ccv/u2bvEJANHUwONKC92vb5bkdPheb855cRo5ATOgrYuCdZPrXfNhAA+Re361mV7nnm7x4s7A4Ac+msbTW0G5xkVlcbVsNxtaIqCHg3/XuuPzwNoMzir4Hu45xRuX3O0cuvxcxmuS2dE29MsKNCKQZLheWF1pVOyrePzMN/igP1/y+WnSo7NOI1F5u9HfSOnCPo1z66COdQcDNl7ubRHALsOE=
    - secure: qlLUwruqSerqtkG++HxHnChtJzI1vlgDR/25UQ4QUDcEzLR8n9iWaBER0PWVOmgKIfaq5tnZWKyHImDCv7XYecCmd5ENlaGT9qQLUzfT3rUELJ5d5CXCKTdT9kDF5Isi7c1tTrBjgPzWcyMCKrP+KVKzhtbPB1YIX/WdWlZ2NxjPq61T79SPdqP1jOOVZ61BLnz6TPEkgMHAbZdJuAadtjGOE9RorsF1ZBQ0PnMG6Cx51p9kzG0VmWPMEP1r59Zv6J6zpi5sh7IhRf53pm0EtALPqITIc4+bmTUrTULZZGVjVr02DQ3F60xIXYGWNxDbXXc4YTau1v+xsFSxHDDPP1c+hd444NE5E8RvWe29vk0QZv0R41FMvDO+Y80csZffMi1rpnF1A8M+AZFiYk/Y059WG+0RpYBcQSqI2ooiPmp3sNV+BvZ3Xkmg7xF4XnPCCVZVSSBL6S3lKlShJ146mQ8wa8pxiJrSGtwdZyHhimO5xJQy2YnPomO790gbTCkHJzgESWzsTmsEsQtW4w872ejj0wkmDVCW7XHSwlAi+MbnurnPO2fCv/fL7lL7Gvv5/ggK7GdlMuujkuHkyITJAfVyo5/JvaOdRPcE+2NhFO328+zwYzPjRvMwT2AUIgqgcr8G798+jAOn4tpYEKNaPfLnL7QslTsnFbJrjLu+PwQ=
