language: java

jdk:
  - openjdk11
  - openjdk8

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"

env:
  global:
    - secure: S0PfSIir3nJkiaOn0Qa3VXDrAJ26AQZ6ptBdpM7XUg7SbAp5KjqMcYDb8P+cF73t/SMf1FqfQ2TJ1v3VgRe9k44OlGFmHXZJ2cWKGn/KTRdAF1l1N3inaSJs9an5XwSxC96AjvWjelATW7sOP520Yu1rgFHB0b4qVUGFQz+2cuqw/UWIxJ8Z7ZWhMv8FEDOtNRaXq93DSCSLVluYUH2Hb0xsXzOan2YjYzaRvHxRmhAO07JItpQBtfsF7BQJIpIWEPYWv91K7XOH5a9oQPJfNIVYW1fxxGKsrrFsqJ8V3bn7IyBdDbXWSv0TlCpSWwWal8YOcksFdTwdY6o5/tsWnVkLWnef2KH3d1YfYpgt7ASJLPANTDEUMy962E1MfsCzk7NO3fOh6VJcdfvyaVBvGVxv8Y/YaYLZetPl5HDy4cDPFJQoLSYYyull729+4Q6Le3tj1N5nL7nyLpgutDhRkbFn9b6F4EZJO3g8fiAznTuFb1X9lIajDKkPsg3ngz36fbIr2rcMgqey7B3nQbbKaJKZWi36c+cZofE+NatykrdMUumEUfvrBaeIAfbh8eqgDxhOQiMZpEVSl3OPrFgxGom8dgF0NA9gEgV6kHJhDHq3EGFLwOckPZiGa3oLE9eqwME+9hQZ9o/Z6NmhX34qhI/RhNGnA1cm51upDnEwxNo=
    - secure: pSyqWiRvm7RkMYSo+nZXkzk2/hVdY0xNR0ObpdbKd1Dd7JCxylwDKIezSC+qAUcb0thpNm9pa6hRHH+LfD4mgYAL0FvpLzkyyyLfdMjL1A0Q/VAZxARO2o4B0ErcinrofYUBerNSKfdd9yiPXC5Fq0XYyunrJ7h6g4SaYZRVnAfaNbbsXHMtqg9vWPRU1xfXz1nvzOEFkMX2BrbOYcjLAiENX4EysOyLlQQ7a2s8CoTdU4xU9PPmqypm3kyrhMerAnSva9xkGk5L2IgwD9CzwDE2f8Q+Yx7cM6Zw4l+etXngpqKp4puayQKCQ/hLPOtJWonYMHdtQfGUM4luYEWoP0SeLIU4jycYWQt/Nv+DENYvOJPckFnk1DR7nWXKH4jhrIr8TgFu5OT/LFGXNN888RroEmn5NfvCVe4XfBMPhICwHD5z2Mn76A6XxGfFFxopvtjr3UL+t6Kn8XWDipi20D40qry17g9spGvFmskob0RDFqu7YEgNkWczB/kQI30PE/bKoR3Mjh9q23JxZEYjm1knGywIz29RXsJJepBsYlHVSA6RFZ0uJK+BVb0Yemae0OaLVWagNqSZBZD/sPiFJWufsxyYyG+2vr/dFKyyW1/CdO12uwAZWGzEtYCetwleFdPlig7fmrP9ciG6H1QYshV1JQuDbCBo8pEdKrMDrMQ=
